#!/usr/bin/env python3
"""Compiles the vendored library's licence into the app.

Called by Scripts/vendor-libwebp.sh. The licence asks that its notice travel
with every binary, and Scripts/build-app.sh assembles the bundle from the
executable alone, so a text file in Resources would never ship. Compiling the
notice in is the version that cannot be left behind.
"""
import pathlib
import sys

dest = pathlib.Path(sys.argv[1])
version = sys.argv[2]
out_path = pathlib.Path(sys.argv[3])

copying = (dest / "COPYING").read_text()
patents = (dest / "PATENTS").read_text()


def lines(text):
    return "\n".join(
        '        "' + line.replace("\\", "\\\\").replace('"', '\\"') + '",'
        for line in text.rstrip("\n").split("\n"))


out = f'''// Generated by Scripts/vendor-libwebp.sh. Do not edit by hand.
//
// The one piece of code in this app that somebody else wrote comes with a
// licence asking that its notice travel with every binary carrying it. So the
// notice is compiled in, and the app menu has a way to read it.
enum OpenSourceNotices {{

    static let title = "Open Source Notices"

    static let intro =
        "Photonz writes WebP files using libwebp {version}, "
        + "which is used under the licence below."

    static let text: String = ([
{lines(copying)}
        "",
        "Additional IP Rights Grant (Patents)",
        "",
{lines(patents)}
    ] as [String]).joined(separator: "\\n")
}}
'''
out_path.write_text(out)
print(f"==> Wrote {out_path}")
